apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "todo-app.fullname" . }}
  labels:
    {{- include "todo-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "todo-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "todo-app.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: {{ template "todo-app.fullname" . }}-postgres
            - name: DB_PORT
              value: {{ .Values.postgresql.servicePort | quote }}
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ template "todo-app.fullname" . }}-postgres-secret
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "todo-app.fullname" . }}-postgres-secret
                  key: password
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
