apiVersion: v1
kind: Service
metadata:
  name: {{ template "todo-app.fullname" . }}-postgres
  labels:
    app: {{ template "todo-app.fullname" . }}
spec:
  ports:
    - port: 5432
  selector:
    app: {{ template "todo-app.fullname" . }}
    tier: postgres
